version = 0.1
[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "minecraft-server-dashboard"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rbs9aclbwmio"
s3_prefix = "minecraft-server-dashboard"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = "ProjectName=\"minecraft-dashboard\" AppValue=\"minecraft\" MinecraftWorkingDir=\"/opt/minecraft/server/\" MinecraftRunCommand=\"sudo screen -d -m java -Xmx3G -Xms3G -jar server.jar nogui &\" AdminEmail=\"arturlr@gmail.com\""
image_repositories = []

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "minecraft-server-dashboard"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-tv5fka8ymyxs"
s3_prefix = "minecraft-server-dashboard"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = "ProjectName=\"minecraft-dashboard\" AppValue=\"minecraft\" MinecraftWorkingDir=\"/opt/minecraft/server/\" MinecraftRunCommand=\"sudo screen -d -m java -Xmx3G -Xms3G -jar server.jar nogui &\" AdminEmail=\"arturlr@gmail.com\""
image_repositories = []
