AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    "MineDash Backend \n"

Parameters:  

  ProjectName:
    Type: String
    Default: minecraft-dashboard
  AppValue:
    Type: String
    Default: minecraft
  AdminEmail:
    Type: String
    Description: Email (Gmail) that is going to be identified as the app admin
    AllowedPattern: '[^@]+@[^@]+\.[^@]+'
    
Globals:
  Function:
    AutoPublishAlias: live
    Handler: index.handler
    MemorySize: 256
    Runtime: python3.8
    Timeout: 120
    Tracing: Active
    Layers: 
      - !Ref HelperLayer

Resources:

  Ec2MinecraftDashboardInstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Description: EC2 MinecraftDashboard Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: cloudwatchMetric
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - 'cloudwatch:PutMetricData'
                  - 'cloudwatch:List*'
                  - 'cloudwatch:Get*'
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  IAMEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: !Sub AWSEC2MinecraftProfile-${AWS::Region}
      Roles: 
        - !Ref Ec2MinecraftDashboardInstanceRole

  AmazonCloudWatchLinuxParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /amplify/minecraftserverdashboard/amazoncloudwatch-linux
      Type: String
      Value: '{ "agent": { "metrics_collection_interval": 60, "run_as_user": "root" }, "logs": { "logs_collected": { "files": { "collect_list": [ { "file_path": "/opt/minecraft/server/logs/latest.log", "log_group_name": "/minecraft/serverlog/{instance_id}", "retention_in_days": 3, "filters": [ { "type": "include", "expression": "Server thread/INFO" } ] } ] } } }, "metrics": { "append_dimensions": { "AutoScalingGroupName": "${aws:AutoScalingGroupName}", "InstanceId": "${aws:InstanceId}" }, "metrics_collected": { "collectd": { "metrics_aggregation_interval": 60 }, "cpu": { "measurement": [ "cpu_usage_active" ], "resources": [ "*" ], "metrics_collection_interval": 60 }, "net": { "measurement": [ "net_bytes_sent" ], "metrics_collection_interval": 60 }, "mem": { "measurement": [ "mem_used_percent" ], "metrics_collection_interval": 60 }, "statsd": { "metrics_aggregation_interval": 60, "metrics_collection_interval": 10, "service_address": ":8125" } } } }'
      Description: Amazon CloudWatch agent config

  AdminEmailParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /amplify/minecraftserverdashboard/adminemail
      Type: String
      Value: !Ref AdminEmail
      Description: Email (Gmail) that is going to be identified as the app admin

  InstancesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: region
          AttributeType: S
        - AttributeName: instanceId
          AttributeType: S
      KeySchema:
        - AttributeName: instanceId
          KeyType: HASH
        - AttributeName: region
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: expiration
        Enabled: true

  HelperLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: MinecraftDashboardHelper
      ContentUri: ./layers/helpers/
      CompatibleRuntimes:
        - python3.8
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile

  ScheduledRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "ScheduledRule"
      ScheduleExpression: "rate(1 minute)"
      State: "DISABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "EventResponse"
              - "Arn"
          Id: "EventResponseV1"

  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref "EventResponse"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "ScheduledRule"
          - "Arn"

  ScheduledRuleParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /amplify/minecraftserverdashboard/scheduledrule
      Type: String
      Value: !Ref ScheduledRule
      Description: ScheduledRule

  EventResponse:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: minecraft-server-dashboard-eventResponse
      CodeUri: ./lambdas/eventResponse/
      Events:
        EC2StateTrigger:
          Type: CloudWatchEvent 
          Properties:
            Pattern:
              source:
                - aws.ec2
              detail-type:
                - EC2 Instance State-change Notification                
      Policies:
        - CostExplorerReadOnlyPolicy: {}
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSCloudTrail_ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonCognitoReadOnly
        - SSMParameterReadPolicy:
            ParameterName: "amplify/minecraftserverdashboard*"
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - logs:Get*
                - logs:List*
                - logs:StartQuery
              Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/minecraft/*'
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - appsync:ListGraphqlApis
                - appsync:GetGraphqlApi
                - appsync:GraphQL
              Resource: '*'
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - events:ListRules
                - events:DescribeRule
                - events:DisableRule
                - events:EnableRule
              Resource: "*"
      Environment:
        Variables:
          APP_NAME: !Ref ProjectName
          TAG_APP_VALUE: !Ref AppValue
          APPSYNC_URL: '{{resolve:ssm:/amplify/minecraftserverdashboard/appsyncurl:1}}'
          USERPOOL_ID: '{{resolve:ssm:/amplify/minecraftserverdashboard/userpoolid:1}}'
          INSTANCES_TABLE_NAME: !Ref InstancesTable
          EC2_INSTANCE_PROFILE_NAME: !Ref IAMEC2InstanceProfile
          EC2_INSTANCE_PROFILE_ARN: !GetAtt IAMEC2InstanceProfile.Arn

  ListServers:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: minecraft-server-dashboard-listServers
      CodeUri: ./lambdas/listServers/
      Policies:
        - CostExplorerReadOnlyPolicy: {}
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSCloudTrail_ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonCognitoReadOnly
        - SSMParameterReadPolicy:
            ParameterName: "amplify/minecraftserverdashboard*"
        - DynamoDBCrudPolicy:
            TableName: !Ref InstancesTable
      Environment:
        Variables:
          APP_NAME: !Ref ProjectName
          TAG_APP_VALUE: !Ref AppValue
          APPSYNC_URL: '{{resolve:ssm:/amplify/minecraftserverdashboard/appsyncurl:1}}'
          INSTANCES_TABLE_NAME: !Ref InstancesTable
          EC2_INSTANCE_PROFILE_NAME: !Ref IAMEC2InstanceProfile
          EC2_INSTANCE_PROFILE_ARN: !GetAtt IAMEC2InstanceProfile.Arn

  GetMonthlyCost:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: minecraft-server-dashboard-getMonthlyCost
      CodeUri: ./lambdas/getMonthlyCost/
      Policies:
        - CostExplorerReadOnlyPolicy: {}
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSCloudTrail_ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonCognitoReadOnly
        - SSMParameterReadPolicy:
            ParameterName: "amplify/minecraftserverdashboard*"
        - DynamoDBCrudPolicy:
            TableName: !Ref InstancesTable
      Environment:
        Variables:
          APP_NAME: !Ref ProjectName
          TAG_APP_VALUE: !Ref AppValue
          APPSYNC_URL: '{{resolve:ssm:/amplify/minecraftserverdashboard/appsyncurl:1}}'
          INSTANCES_TABLE_NAME: !Ref InstancesTable

  TriggerServerAction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: minecraft-server-dashboard-triggerServerAction
      CodeUri: ./lambdas/triggerServerAction/
      Policies:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonCognitoReadOnly
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt StateMachine.Name
        - SSMParameterReadPolicy:
            ParameterName: "amplify/minecraftserverdashboard*"
        - DynamoDBCrudPolicy:
            TableName: !Ref InstancesTable
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - ec2:AssociateIamInstanceProfile
                - ec2:DisassociateIamInstanceProfile
              Resource: '*'
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource: !GetAtt Ec2MinecraftDashboardInstanceRole.Arn
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - ssm:PutParameter
                - ssm:GetParameters          
              Resource: !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/amplify/minecraftserverdashboard*
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:CreateGroup
                - cognito-idp:AdminAddUserToGroup
                - cloudwatch:PutMetricAlarm
              Resource: '*'
            
      Environment:
        Variables: 
          StepFunctionsArn: !Ref StateMachine
          APP_NAME: !Ref ProjectName
          TAG_APP_VALUE: !Ref AppValue
          APPSYNC_URL: '{{resolve:ssm:/amplify/minecraftserverdashboard/appsyncurl:1}}'
          INSTANCES_TABLE_NAME: !Ref InstancesTable
          EC2_INSTANCE_PROFILE_NAME: !Ref IAMEC2InstanceProfile
          EC2_INSTANCE_PROFILE_ARN: !GetAtt IAMEC2InstanceProfile.Arn
          CONFIG_SERVER_LAMBDA_NAME: !Ref ConfigServer

  ChangeServerState:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: minecraft-server-dashboard-changeServerState
      CodeUri: ./lambdas/stepFunctions/changeServerState/
      Policies:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonCognitoReadOnly
        - SSMParameterReadPolicy:
            ParameterName: "amplify/minecraftserverdashboard*"
        - DynamoDBCrudPolicy:
            TableName: !Ref InstancesTable
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - ec2:StartInstances
                - ec2:StopInstances
                - ec2:RebootInstances
              Resource: '*'
      Environment:
        Variables:
          APP_NAME: !Ref ProjectName
          TAG_APP_VALUE: !Ref AppValue
          APPSYNC_URL: '{{resolve:ssm:/amplify/minecraftserverdashboard/appsyncurl:1}}'
          USERPOOL_ID: '{{resolve:ssm:/amplify/minecraftserverdashboard/userpoolid:1}}'
          INSTANCES_TABLE_NAME: !Ref InstancesTable

  ConfigServer:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: minecraft-server-dashboard-configServer
      CodeUri: ./lambdas/stepFunctions/configServer/
      Policies:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
        - SSMParameterReadPolicy:
            ParameterName: "amplify/minecraftserverdashboard*"
        - DynamoDBCrudPolicy:
            TableName: !Ref InstancesTable
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - ssm:List*
                - ssm:Describe*
                - ssm:Get*
                - ssm:SendCommand
                - ec2:AssociateIamInstanceProfile
                - ec2:DisassociateIamInstanceProfile
              Resource: '*'
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource: !GetAtt Ec2MinecraftDashboardInstanceRole.Arn
      Environment:
        Variables:
          APP_NAME: !Ref ProjectName
          TAG_APP_VALUE: !Ref AppValue
          APPSYNC_URL: '{{resolve:ssm:/amplify/minecraftserverdashboard/appsyncurl:1}}'
          INSTANCES_TABLE_NAME: !Ref InstancesTable
          

  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ./lambdas/stepFunctions/step-functions.json
      DefinitionSubstitutions:
        changeServerState: !GetAtt ChangeServerState.Arn
        configServer: !GetAtt ConfigServer.Arn
      Role: !GetAtt StatesExecutionRole.Arn
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
             LogGroupArn: !GetAtt StateMachineLogGroup.Arn

  StateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/states/${ProjectName}-StateMachine-LogGroup-${AWS::Region}'
  
  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
      Policies:        
        - PolicyName: steprolep1
          PolicyDocument:
            Version: "2012-10-17"      
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - ssm:SendCommand
                  - ssm:List*
                  - ssm:Get*
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                Resource: "*"

Outputs:
  StateMachineArn:
        Value: !Ref StateMachine
  StateMachineName:
      Value: !GetAtt StateMachine.Name
  EventResponseArn:
      Value: !GetAtt EventResponse.Arn
  ListServersArn:
      Value: !GetAtt ListServers.Arn
  ConfigServerArn:
      Value: !GetAtt ConfigServer.Arn