AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  env:
    Type: String
  apiminecraftserverdashbGraphQLAPIIdOutput:
    Type: String
    Description: >-
      Input parameter describing GraphQLAPIIdOutput attribute for
      api/minecraftserverdashb resource
  apiminecraftserverdashbGraphQLAPIEndpointOutput:
    Type: String
    Description: >-
      Input parameter describing GraphQLAPIEndpointOutput attribute for
      api/minecraftserverdashb resource
Resources:
  ChangeServerStateDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId:
        Ref: apiminecraftserverdashbGraphQLAPIIdOutput
      Name: ChangeServerStateDataSource
      Type: NONE
  ChangeServerStateResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Ref: apiminecraftserverdashbGraphQLAPIIdOutput
      TypeName: Mutation
      FieldName: changeServerState
      Kind: UNIT
      DataSourceName:
        Fn::GetAtt:
          - ChangeServerStateDataSource
          - Name
      RequestMappingTemplate: |
        {
          "version" : "2017-02-28",
          "payload": { 
              "id": $util.toJson($context.arguments.input.id),
              "name": $util.toJson($context.arguments.input.name),
              "type": $util.toJson($context.arguments.input.type),
              "userEmail": $util.toJson($context.arguments.input.userEmail),
              "state": $util.toJson($context.arguments.input.state),
              "vCpus": $util.toJson($context.arguments.input.vCpus),
              "memSize": $util.toJson($context.arguments.input.memSize),
              "diskSize": $util.toJson($context.arguments.input.diskSize),
              "launchTime": $util.toJson($context.arguments.input.launchTime),
              "publicIp": $util.toJson($context.arguments.input.publicIp),
              "initStatus": $util.toJson($context.arguments.input.initStatus),
              "iamStatus": $util.toJson($context.arguments.input.iamStatus),
              "runningMinutes": $util.toJson($context.arguments.input.runningMinutes),
              "groupMembers": $util.toJson($context.arguments.input.groupMembers)
          }
        }
      ResponseMappingTemplate: $utils.toJson($ctx.result)
  PutServerMetricDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId:
        Ref: apiminecraftserverdashbGraphQLAPIIdOutput
      Name: PutServerMetricDataSource
      Type: NONE
  PutServerMetricStateResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Ref: apiminecraftserverdashbGraphQLAPIIdOutput
      TypeName: Mutation
      FieldName: putServerMetric
      Kind: UNIT
      DataSourceName:
        Fn::GetAtt:
          - PutServerMetricDataSource
          - Name
      RequestMappingTemplate: |
        {
          "version" : "2017-02-28",
          "payload": { 
              "id": $util.toJson($context.arguments.input.id),
              "cpuStats": $util.toJson($context.arguments.input.cpuStats),
              "networkStats": $util.toJson($context.arguments.input.networkStats),
              "memStats": $util.toJson($context.arguments.input.memStats),
              "activeUsers": $util.toJson($context.arguments.input.activeUsers)
          }
        }
      ResponseMappingTemplate: $utils.toJson($ctx.result)
Outputs:
  ChangeServerStateDataSourceOutput:
    Value:
      Ref: ChangeServerStateDataSource
  ChangeServerStateResolverOutput:
    Value:
      Ref: ChangeServerStateResolver
  PutServerMetricDataSourceOutput:
    Value:
      Ref: PutServerMetricDataSource
  PutServerMetricStateResolverOutput:
    Value:
      Ref: PutServerMetricStateResolver
Description: >-
  {"createdOn":"Mac","createdBy":"Amplify","createdWith":"8.0.1","stackType":"custom-customCloudformation","metadata":{}}
