AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project
  EnvironmentName:
    Type: String
    Description: Name of the environment
  AppValue:
    Type: String
    Description: Value of the application
  SupportBucketName:
    Type: String
    Description: Pre-existing S3 support bucket name from CircleCI
  FrontendBucketName:
    Type: String
    Description: Pre-existing S3 frontend bucket name from CircleCI


Resources:

  DynamoDBStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/dynamodb.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        AppValue: !Ref AppValue

  CognitoStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/cognito.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        AppValue: !Ref AppValue

  EC2Stack:
    Type: AWS::Serverless::Application
    DependsOn: DynamoDBStack
    Properties:
      Location: ./templates/ec2.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        AppValue: !Ref AppValue
        SupportBucketName: !Ref SupportBucketName

  SSMStack:
    Type: AWS::Serverless::Application
    DependsOn: DynamoDBStack
    Properties:
      Location: ./templates/ssm.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        AppValue: !Ref AppValue
        SupportBucket: !Ref SupportBucketName

  LambdasStack:
    Type: AWS::Serverless::Application
    DependsOn: 
      - CognitoStack
      - DynamoDBStack
      - EC2Stack
    Properties:
      Location: ./templates/lambdas.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        AppValue: !Ref AppValue
        BootstrapSSMDoc: !GetAtt SSMStack.Outputs.BootstrapSSMDoc
        IAMEC2RoleArn: !GetAtt EC2Stack.Outputs.IAMEC2RoleArn
        IAMEC2InstanceProfile: !GetAtt EC2Stack.Outputs.IAMEC2InstanceProfile
        IAMEC2InstanceProfileArn: !GetAtt EC2Stack.Outputs.IAMEC2InstanceProfileArn

Outputs:
  GraphQLAPIEndpoint:
    Description: AppSync GraphQL API Endpoint
    Value: !GetAtt LambdasStack.Outputs.GraphQLAPIEndpoint

  CognitoUserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !GetAtt CognitoStack.Outputs.CognitoUserPoolClientId

  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !GetAtt CognitoStack.Outputs.CognitoUserPoolId

  CognitoIdentityPool:
    Description: Cognito Identity Pool ID
    Value: !GetAtt CognitoStack.Outputs.CognitoIdentityPool

  CognitoDomainName:
    Description: Cognito Domain Name
    Value: !GetAtt CognitoStack.Outputs.CognitoDomainName

  SupportBucket:
    Description: S3 Support Bucket Name
    Value: !Ref SupportBucketName

  FrontendBucket:
    Description: S3 Frontend Bucket Name
    Value: !Ref FrontendBucketName
