AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project
  EnvironmentName:
    Type: String
    Description: Name of the environment
  AppValue:
    Type: String
    Description: Value of the application

Resources:

  CognitoStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/cognito.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        AppValue: !Ref AppValue

  EC2Stack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./templates/ec2.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        AppValue: !Ref AppValue

  LambdasStack:
    Type: AWS::Serverless::Application
    DependsOn: 
      - EC2Stack
      - CognitoStack
    Properties:
      Location: ./templates/lambdas.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        AppValue: !Ref AppValue

  AppSyncStack:
    Type: AWS::Serverless::Application
    DependsOn: 
      - LambdasStack
    Properties:
      Location: ./templates/appsync.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        AppValue: !Ref AppValue

  WebStack:
    Type: AWS::Serverless::Application
    DependsOn: 
      - EC2Stack
      - CognitoStack
    Properties:
      Location: ./templates/web.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        AppValue: !Ref AppValue

Outputs:
  GraphQLAPIEndpoint:
    Description: AppSync GraphQL API Endpoint
    Value: 
      Fn::ImportValue: !Sub "${ProjectName}-${EnvironmentName}-GraphQLAPIEndpoint"

  CloudFrontDomain:
    Description: CloudFront Distribution Domain Name
    Value: 
      Fn::ImportValue: !Sub "${ProjectName}-${EnvironmentName}-CloudFrontDomain"

  CognitoUserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: 
      Fn::ImportValue: !Sub "${ProjectName}-${EnvironmentName}-UserPoolClientId"

  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: 
      Fn::ImportValue: !Sub "${ProjectName}-${EnvironmentName}-UserPoolId"

  CognitoIdentityPool:
    Description: Cognito Identity Pool ID
    Value: 
      Fn::ImportValue: !Sub "${ProjectName}-${EnvironmentName}-CognitoIdentityPool"

  CognitoDomainName:
    Description: Cognito Domain Name
    Value: 
      Fn::ImportValue: !Sub "${ProjectName}-${EnvironmentName}-CognitoDomainName"

  WebAppBucket:
    Description: S3 Web Application Bucket Name
    Value: 
      Fn::ImportValue: !Sub "${ProjectName}-${EnvironmentName}-WebBucket"

  SupportBucket:
    Description: S3 Support Bucket Name
    Value: 
      Fn::ImportValue: !Sub "${ProjectName}-${EnvironmentName}-SupportBucket"
