AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
  EnvironmentName:
    Type: String
  AppValue:
    Type: String    

Resources:
  
  DataSourceNone:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId:  
        Fn::ImportValue: 
          !Sub "${ProjectName}-${EnvironmentName}-GraphQLAPIId"
      Name: dataSourceNameNone
      Description: dataSourceNone
      Type: "NONE"

  PutMetricServerResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:  
        Fn::ImportValue: 
          !Sub "${ProjectName}-${EnvironmentName}-GraphQLAPIId"
      TypeName: Mutation
      FieldName: putServerMetric
      DataSourceName: !GetAtt DataSourceNone.Name
      RequestMappingTemplate: |
        {
          "version" : "2017-02-28",
          "payload": { 
              "id": $util.toJson($context.arguments.input.id),
              "cpuStats": $util.toJson($context.arguments.input.cpuStats),
              "networkStats": $util.toJson($context.arguments.input.networkStats),
              "memStats": $util.toJson($context.arguments.input.memStats),
              "activeUsers": $util.toJson($context.arguments.input.activeUsers),
          }
        }
      ResponseMappingTemplate: $util.toJson($ctx.result)

  ChangeServerStateResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:  
        Fn::ImportValue: 
          !Sub "${ProjectName}-${EnvironmentName}-GraphQLAPIId"
      TypeName: Mutation
      FieldName: changeServerState
      DataSourceName: !GetAtt DataSourceNone.Name
      RequestMappingTemplate: |
        {
          "version" : "2017-02-28",
          "payload": { 
              "id": $util.toJson($context.arguments.input.id),
              "name": $util.toJson($context.arguments.input.name),
              "type": $util.toJson($context.arguments.input.type),
              "userEmail": $util.toJson($context.arguments.input.userEmail),
              "state": $util.toJson($context.arguments.input.state),
              "vCpus": $util.toJson($context.arguments.input.vCpus),
              "memSize": $util.toJson($context.arguments.input.memSize),
              "diskSize": $util.toJson($context.arguments.input.diskSize),
              "launchTime": $util.toJson($context.arguments.input.launchTime),
              "publicIp": $util.toJson($context.arguments.input.publicIp),
              "initStatus": $util.toJson($context.arguments.input.initStatus),
              "iamStatus": $util.toJson($context.arguments.input.iamStatus),
              "runningMinutes": $util.toJson($context.arguments.input.runningMinutes),
              "groupMembers": $util.toJson($context.arguments.input.groupMembers)
          }
        }
      ResponseMappingTemplate: $util.toJson($ctx.result)

  PutServerActionStatusResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:  
        Fn::ImportValue: 
          !Sub "${ProjectName}-${EnvironmentName}-GraphQLAPIId"
      TypeName: Mutation
      FieldName: putServerActionStatus
      DataSourceName: !GetAtt DataSourceNone.Name
      RequestMappingTemplate: |
        {
          "version" : "2017-02-28",
          "payload": { 
              "id": $util.toJson($context.arguments.input.id),
              "action": $util.toJson($context.arguments.input.action),
              "status": $util.toJson($context.arguments.input.status),
              "timestamp": $util.toJson($context.arguments.input.timestamp),
              "message": $util.toJson($context.arguments.input.message),
              "userEmail": $util.toJson($context.arguments.input.userEmail)
          }
        }
      ResponseMappingTemplate: $util.toJson($ctx.result)

  # PutServerConfigResolver:
  #   Type: AWS::AppSync::Resolver
  #   Properties:
  #     ApiId:  
  #       Fn::ImportValue: 
  #         !Sub "${ProjectName}-${EnvironmentName}-GraphQLAPIId"
  #     TypeName: Mutation
  #     FieldName: putServerConfig
  #     DataSourceName: !GetAtt DataSourceNone.Name
  #     RequestMappingTemplate: |
  #       {
  #         "version" : "2017-02-28",
  #         "payload": { 
  #             "id": $util.toJson($context.arguments.input.id),
  #             "shutdownMethod": $util.toJson($context.arguments.input.shutdownMethod),
  #             "scheduleExpression": $util.toJson($context.arguments.input.scheduleExpression),             
  #             "alarmThreshold": $util.toJson($context.arguments.input.alarmThreshold),
  #             "alarmEvaluationPeriod": $util.toJson($context.arguments.input.alarmEvaluationPeriod),
  #             "runCommand": $util.toJson($context.arguments.input.runCommand),
  #             "workDir": $util.toJson($context.arguments.input.workDir)
  #         }
  #       }
  #     ResponseMappingTemplate: $util.toJson($ctx.result)

  # PutServerUsersResolver:
  #   Type: AWS::AppSync::Resolver
  #   Properties:
  #     ApiId:  
  #       Fn::ImportValue: 
  #         !Sub "${ProjectName}-${EnvironmentName}-GraphQLAPIId"
  #     TypeName: Mutation
  #     FieldName: putServerUsers
  #     DataSourceName: !GetAtt DataSourceNone.Name
  #     RequestMappingTemplate: |
  #       {
  #         "version" : "2017-02-28",
  #         "payload": { 
  #             "id": $util.toJson($context.arguments.input.id),
  #             "groupMembers": $util.toJson($context.arguments.input.groupMembers)
  #         }
  #       }
  #     ResponseMappingTemplate: $util.toJson($ctx.result)

