AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
  EnvironmentName:
    Type: String
  AppValue:
    Type: String
    Description: Value of the application
  SupportBucketName:
    Type: String
    Description: Pre-existing S3 support bucket name from CircleCI

Resources:

  Ec2MinecraftDashboardInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      Description: EC2 MinecraftDashboard Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: cloudwatchMetric
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "cloudwatch:PutMetricData"
                  - "cloudwatch:DescribeAlarms"
                  - "cloudwatch:GetMetricStatistics"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "ssm:DescribeParameters"
                  - "ssm:PutParameter"
                  - "ssm:GetParameter"
                  - "ssm:GetParameters"
                Resource:
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/minecraft-dashboard/jwt-secret"
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/minecraft-dashboard/rcon-password"
        - PolicyName: cloudwatchLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:DescribeLogStreams"
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/minecraft-dashboard/*"
        - PolicyName: ecrAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ecr:GetAuthorizationToken"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"
                Resource:
                  - !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/msd-metrics"
                  - !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/msd-logs"
        - PolicyName: dynamoDBServersTableAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:UpdateItem"
                  - "dynamodb:PutItem"
                Resource:
                  Fn::ImportValue: !Sub "${ProjectName}-${EnvironmentName}-CoreTable"
        - PolicyName: ec2TagsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:DescribeTags"
                Resource: "*"
        - PolicyName: s3SupportBucketAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:ListBucket"
                Resource:
                  - !Sub "arn:aws:s3:::${SupportBucketName}"
                  - !Sub "arn:aws:s3:::${SupportBucketName}/*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  IAMEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub AWSEC2MinecraftProfile-${EnvironmentName}-${AWS::Region}
      Roles:
        - !Ref Ec2MinecraftDashboardInstanceRole

Outputs:
  SupportBucket:
    Description: SupportBucket
    Value: !Ref SupportBucketName
    Export:
      Name: !Sub "${ProjectName}-${EnvironmentName}-SupportBucket"

  IAMEC2InstanceProfile:
    Description: IAMEC2InstanceProfile
    Value: !Ref IAMEC2InstanceProfile
    Export:
      Name: !Sub "${ProjectName}-${EnvironmentName}-IAMEC2InstanceProfile"

  IAMEC2InstanceProfileArn:
    Description: IAMEC2InstanceProfileArn
    Value: !GetAtt IAMEC2InstanceProfile.Arn
    Export:
      Name: !Sub "${ProjectName}-${EnvironmentName}-IAMEC2InstanceProfileArn"

  IAMEC2RoleArn:
    Description: IAMEC2RoleArn
    Value: !GetAtt Ec2MinecraftDashboardInstanceRole.Arn
    Export:
      Name: !Sub "${ProjectName}-${EnvironmentName}-IAMEC2RoleArn"
