AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
  EnvironmentName:
    Type: String
  AppValue:
    Type: String
    Description: Value of the application

Resources:

  SupportBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    DeletionPolicy: Delete

  Ec2MinecraftDashboardInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      Description: EC2 MinecraftDashboard Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: cloudwatchMetric
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "cloudwatch:PutMetricData"
                  - "cloudwatch:List*"
                  - "cloudwatch:Get*"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "ssm:DescribeParameters"
                  - "ssm:PutParameter"
                  - "ssm:GetParameter"
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/minecraft*"
        - PolicyName: ec2TagsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:DescribeTags"
                Resource: "*"
        - PolicyName: s3SupportBucketAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:ListBucket"
                Resource:
                  - !Sub "${SupportBucket.Arn}"
                  - !Sub "${SupportBucket.Arn}/*"
        - PolicyName: dynamoDBServersTableAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:UpdateItem"
                  - "dynamodb:GetItem"
                Resource:
                  Fn::ImportValue: !Sub "${ProjectName}-${EnvironmentName}-ServersTable"

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  IAMEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub AWSEC2MinecraftProfile-${AWS::Region}
      Roles:
        - !Ref Ec2MinecraftDashboardInstanceRole

  # CloudWatch agent config is now stored in S3 and referenced from there
  # The amazon-cloudwatch-agent.json file is uploaded to S3 by deployment scripts
                    exit 1
                  fi
                  echo "✓ Port count cron job is configured"
                  
                  if ! crontab -l | grep -q "network_monitor.sh"; then
                    echo "ERROR: Network monitor cron job not configured"
                    exit 1
                  fi
                  echo "✓ Network monitor cron job is configured"
                  
                  # Update DynamoDB to mark as bootstrapped
                  echo "Updating DynamoDB table: $TABLE_NAME"
                  aws dynamodb update-item \
                    --table-name "$TABLE_NAME" \
                    --key "{\"id\": {\"S\": \"$INSTANCE_ID\"}}" \
                    --update-expression "SET isBootstrapComplete = :bootstrapped, updatedAt = :timestamp" \
                    --expression-attribute-values "{\":bootstrapped\": {\"BOOL\": true}, \":timestamp\": {\"S\": \"$TIMESTAMP\"}}" \
                    --region "$REGION"
                  
                  if [ $? -eq 0 ]; then
                    echo "✓ Successfully marked instance as bootstrapped in DynamoDB"
                    echo "Bootstrap process completed successfully!"
                  else
                    echo "ERROR: Failed to update DynamoDB"
                    exit 1
                  fi

Outputs:
  SupportBucket:
    Description: SupportBucket
    Value: !Ref SupportBucket
    Export:
      Name: !Sub "${ProjectName}-${EnvironmentName}-SupportBucket"

  IAMEC2InstanceProfile:
    Description: IAMEC2InstanceProfile
    Value: !Ref IAMEC2InstanceProfile
    Export:
      Name: !Sub "${ProjectName}-${EnvironmentName}-IAMEC2InstanceProfile"

  IAMEC2InstanceProfileArn:
    Description: IAMEC2InstanceProfileArn
    Value: !GetAtt IAMEC2InstanceProfile.Arn
    Export:
      Name: !Sub "${ProjectName}-${EnvironmentName}-IAMEC2InstanceProfileArn"

  IAMEC2RoleArn:
    Description: IAMEC2RoleArn
    Value: !GetAtt Ec2MinecraftDashboardInstanceRole.Arn
    Export:
      Name: !Sub "${ProjectName}-${EnvironmentName}-IAMEC2RoleArn"
