AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
  EnvironmentName:
    Type: String
  AppValue:
    Type: String
    Description: Value of the application

Resources:

  SupportBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    DeletionPolicy: Delete

  Ec2MinecraftDashboardInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      Description: EC2 MinecraftDashboard Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: cloudwatchMetric
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "cloudwatch:PutMetricData"
                  - "cloudwatch:List*"
                  - "cloudwatch:Get*"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "ssm:DescribeParameters"
                  - "ssm:PutParameter"
                  - "ssm:GetParameter"
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/minecraft*"
        - PolicyName: dynamoDBServersTableAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:UpdateItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:GetItem"
                Resource:
                  Fn::ImportValue: !Sub "${ProjectName}-${EnvironmentName}-CoreTableArn"
        - PolicyName: ec2TagsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:DescribeTags"
                Resource: "*"
        - PolicyName: s3SupportBucketAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:ListBucket"
                Resource:
                  - !Sub "${SupportBucket.Arn}"
                  - !Sub "${SupportBucket.Arn}/*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  IAMEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub AWSEC2MinecraftProfile-${AWS::Region}
      Roles:
        - !Ref Ec2MinecraftDashboardInstanceRole

Outputs:
  SupportBucket:
    Description: SupportBucket
    Value: !Ref SupportBucket
    Export:
      Name: !Sub "${ProjectName}-${EnvironmentName}-SupportBucket"

  IAMEC2InstanceProfile:
    Description: IAMEC2InstanceProfile
    Value: !Ref IAMEC2InstanceProfile
    Export:
      Name: !Sub "${ProjectName}-${EnvironmentName}-IAMEC2InstanceProfile"

  IAMEC2InstanceProfileArn:
    Description: IAMEC2InstanceProfileArn
    Value: !GetAtt IAMEC2InstanceProfile.Arn
    Export:
      Name: !Sub "${ProjectName}-${EnvironmentName}-IAMEC2InstanceProfileArn"

  IAMEC2RoleArn:
    Description: IAMEC2RoleArn
    Value: !GetAtt Ec2MinecraftDashboardInstanceRole.Arn
    Export:
      Name: !Sub "${ProjectName}-${EnvironmentName}-IAMEC2RoleArn"
