AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
  EnvironmentName:
    Type: String
  AppValue:
    Type: String
    Description: Value of the application

Resources:

  SupportBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    DeletionPolicy: Delete

  Ec2MinecraftDashboardInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      Description: EC2 MinecraftDashboard Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: cloudwatchMetric
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "cloudwatch:PutMetricData"
                  - "cloudwatch:List*"
                  - "cloudwatch:Get*"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "ssm:DescribeParameters"
                  - "ssm:PutParameter"
                  - "ssm:GetParameter"
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/minecraft*"

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  IAMEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub AWSEC2MinecraftProfile-${AWS::Region}
      Roles:
        - !Ref Ec2MinecraftDashboardInstanceRole

  AmazonCloudWatchLinuxParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${ProjectName}/${EnvironmentName}/cloudwatch-agent-config
      Type: String
      Value: '{ "agent": { "metrics_collection_interval": 60, "run_as_user": "root" }, "logs": { "logs_collected": { "files": { "collect_list": [ { "file_path": "/opt/minecraft/server/logs/latest.log", "log_group_name": "/minecraft/serverlog/{instance_id}", "retention_in_days": 3, "filters": [ { "type": "include", "expression": "Server thread/INFO" } ] } ] } } }, "metrics": { "append_dimensions": { "AutoScalingGroupName": "${aws:AutoScalingGroupName}", "InstanceId": "${aws:InstanceId}" }, "metrics_collected": { "collectd": { "metrics_aggregation_interval": 60 }, "cpu": { "measurement": [ "cpu_usage_active" ], "resources": [ "*" ], "metrics_collection_interval": 60 }, "net": { "measurement": [ "net_bytes_sent" ], "metrics_collection_interval": 60 }, "mem": { "measurement": [ "mem_used_percent" ], "metrics_collection_interval": 60 }, "statsd": { "metrics_aggregation_interval": 60, "metrics_collection_interval": 10, "service_address": ":8125" } } } }'
      Description: Amazon CloudWatch agent config

  BootstrapSSMDoc:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      TargetType: /AWS::EC2::Instance
      Content:
        schemaVersion: '2.2'
        description: Bootstrap instance
        parameters:
          SSMParameterPrefix:
            type: String
            description: 'SSM parameter prefix'
            default: !Sub /${ProjectName}/${EnvironmentName}
        mainSteps:              
          - action: aws:runShellScript
            name: installPackages
            inputs:
              runCommand:
                - '#!/bin/bash'
                - |
                  # Function to detect the Linux distribution
                  detect_distro() {
                      if [ -f /etc/os-release ]; then
                          . /etc/os-release
                          DISTRO=$ID
                      elif [ -f /etc/lsb-release ]; then
                          . /etc/lsb-release
                          DISTRO=$DISTRIB_ID
                      elif [ -f /etc/debian_version ]; then
                          DISTRO="debian"
                      elif [ -f /etc/redhat-release ]; then
                          DISTRO="rhel"
                      else
                          DISTRO=$(uname -s)
                      fi
                      echo $DISTRO
                  }
                  # Function to install CloudWatch agent on Amazon Linux, RHEL, or CentOS
                  install_cloudwatch_rpm() {
                      # Check if CloudWatch agent is already installed
                      if rpm -q amazon-cloudwatch-agent &> /dev/null; then
                          echo "CloudWatch agent is already installed"
                          return 0
                      fi

                      # Install CloudWatch agent
                      if yum install -y amazon-cloudwatch-agent; then
                          # Verify installation was successful
                          if rpm -q amazon-cloudwatch-agent &> /dev/null; then
                              echo "CloudWatch agent installed successfully"
                              return 0
                          else
                              echo "CloudWatch agent installation failed verification"
                              return 1
                          fi
                      else
                          echo "Failed to install CloudWatch agent"
                          return 1
                      fi
                  }

                  # Function to install CloudWatch agent on Ubuntu or Debian
                  install_cloudwatch_deb() {
                      # Check if CloudWatch agent is already installed
                      if dpkg -l | grep -q "amazon-cloudwatch-agent"; then
                          echo "CloudWatch agent is already installed"
                          return 0
                      fi

                      # Update package list
                      apt-get update

                      # Check if wget is already installed
                      if ! command -v wget &> /dev/null; then
                          echo "Installing wget..."
                          apt-get install -y wget
                      else
                          echo "wget is already installed"
                      fi

                      # Download and install CloudWatch agent
                      if wget https://amazoncloudwatch-agent.s3.amazonaws.com/debian/amd64/latest/amazon-cloudwatch-agent.deb; then
                          if dpkg -i -E ./amazon-cloudwatch-agent.deb; then
                              rm amazon-cloudwatch-agent.deb
                              echo "CloudWatch agent installed successfully"
                          else
                              echo "Failed to install CloudWatch agent"
                              rm amazon-cloudwatch-agent.deb
                              return 1
                          fi
                      else
                          echo "Failed to download CloudWatch agent"
                          return 1
                      fi
                  }

                  install_required_packages() {
                      local packages=("jq" "zip" "unzip" "net-tools")
                      local packages_to_install=()

                      # Check each package
                      for package in "${packages[@]}"; do
                          if ! dpkg -l | grep -q "^ii.*$package "; then
                              echo "$package is not installed"
                              packages_to_install+=("$package")
                          else
                              echo "$package is already installed"
                          fi
                      done

                      # Install missing packages if any
                      if [ ${#packages_to_install[@]} -gt 0 ]; then
                          echo "Installing missing packages: ${packages_to_install[*]}"
                          apt-get update
                          if apt-get install -y "${packages_to_install[@]}"; then
                              echo "Successfully installed missing packages"
                              return 0
                          else
                              echo "Failed to install some packages"
                              return 1
                          fi
                      else
                          echo "All required packages are already installed"
                          return 0
                      fi
                  }

                  install_awscli() {
                      if [ ! -f /usr/share/collectd/types.db ]; then
                        sudo mkdir -p /usr/share/collectd
                        sudo touch /usr/share/collectd/types.db
                      fi
                      if ! command -v aws >/dev/null 2>&1; then
                        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                        unzip awscliv2.zip
                        sudo ./aws/install
                      echo "AWS CLI installed successfully"
                      else
                          echo "AWS CLI is already installed"
                      fi 
                  }
                  # Main installation function
                  install_packages() {
                      local distro=$(detect_distro)
                      case $distro in
                          amzn*|rhel*|centos*)
                              install_cloudwatch_rpm
                              yum -y install jq zip unzip
                              ;;
                          ubuntu*|debian*)
                              install_cloudwatch_deb
                              install_required_packages
                              ;;
                          *)
                              echo "Unsupported distribution: $distro"
                              exit 1
                              ;;
                      esac
                  }
                  
                  install_packages
                  install_awscli

                  echo "Packages installed successfully" 
          - action: aws:runShellScript
            name: CloudWatchStart
            inputs:
              runCommand:
                - |
                  sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c ssm:{{ SSMParameterPrefix }}/cloudwatch-agent-config
                  sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -m ec2 -a status      
          - action: aws:runShellScript
            name: Cron
            inputs:
              runCommand:
                - '#!/bin/bash'
                - !Sub |
                  if [ ! -f /usr/local/port_count.sh ]; then
                    # Get instance metadata
                    INSTANCE_ID=$(ec2metadata --instance-id)
                    REGION=${AWS::Region}
                    # Count established connections on port 25565
                    PORT_COUNT=$(netstat -an | grep ESTABLISHED | grep ':25565' | wc -l)
                    # Create the script file
                    echo "#!/bin/bash" > /usr/local/port_count.sh
                    echo "INSTANCE_ID=\"$INSTANCE_ID\"" >> /usr/local/port_count.sh
                    echo "PORT_COUNT=\$(netstat -an | grep ESTABLISHED | grep ':25565' | wc -l)" >> /usr/local/port_count.sh
                    echo "REGION=\"$REGION\"" >> /usr/local/port_count.sh
                    echo "aws cloudwatch put-metric-data --metric-name UserCount --dimensions InstanceId=\$INSTANCE_ID --namespace 'MinecraftDashboard' --value \$PORT_COUNT --region \$REGION" >> /usr/local/port_count.sh
                    # Make the script executable
                    chmod +x /usr/local/port_count.sh
                    # Schedule the script to run every minute
                    (sudo crontab -l 2>/dev/null; echo "*/1 * * * * /usr/local/port_count.sh >/dev/null 2>&1") | crontab -         
                  fi  
                - sudo crontab -l

          - action: aws:runShellScript
            name: MinecraftS3Backup
            inputs:
              runCommand:
                - '#!/bin/bash'
                - !Sub |
                  if [ ! -f /usr/local/minecraft_s3_backup.sh ]; then
                    MINECRAFT_DIR="$HOME/.minecraft/saves"
                    INSTANCE_ID=$(ec2metadata --instance-id)
                    REGION=${AWS::Region}
                    S3_BUCKET=${SupportBucket}
                    # Creating the script
                    echo "#!/bin/bash" > /usr/local/minecraft_s3_backup.sh
                    echo "INSTANCE_ID=\"$INSTANCE_ID\"" >> /usr/local/minecraft_s3_backup.sh
                    echo "REGION=\"$REGION\"" >> /usr/local/minecraft_s3_backup.sh
                    echo "S3_BUCKET=\"$S3_BUCKET\"" >> /usr/local/minecraft_s3_backup.sh
                    echo "MINECRAFT_DIR=\"$MINECRAFT_DIR\"" >> /usr/local/minecraft_s3_backup.sh
                    echo "DATE=\$(date +%Y-%m-%d_%H-%M-%S)" >> /usr/local/minecraft_s3_backup.sh
                    echo "BACKUP_NAME=\"minecraft_backup_\$DATE.tar.gz\"" >> /usr/local/minecraft_s3_backup.sh
                    echo "tar -cpvzf /tmp/\$BACKUP_NAME \$MINECRAFT_DIR" >> /usr/local/minecraft_s3_backup.sh
                    echo "aws s3 cp /tmp/\$BACKUP_NAME s3://\$S3_BUCKET/\$INSTANCE_ID/\$BACKUP_NAME" >> /usr/local/minecraft_s3_backup.sh
                    echo "rm /tmp/\$BACKUP_NAME" >> /usr/local/minecraft_s3_backup.sh
                    # Optionally, remove old backups (keep last 5)
                    # echo "aws s3 ls s3://\$S3_BUCKET/\$INSTANCE_ID/ | sort | head -n -5 | awk '{print \$4}' | xargs -I {} aws s3 rm s3://\$S3_BUCKET/\$INSTANCE_ID/\$BACKUP_NAME" >> /usr/local/minecraft_s3_backup.sh
                    # Make the script executable
                    chmod +x /usr/local/minecraft_s3_backup.sh
                    # Schedule the script to run every hour
                    (sudo crontab -l 2>/dev/null; echo "0 * * * * /usr/local/minecraft_s3_backup.sh >/dev/null 2>&1") | crontab -
                  fi
                - sudo crontab -l

          - action: aws:runShellScript
            name: NICSSM
            inputs:
              runCommand:
                - echo "Get NIC"
                - NIC=$(ip route get 1.1.1.1 | awk '{print $5; exit}')
                - INSTANCE_ID=$(ec2metadata --instance-id)                
                - PARAM_NAME="{{ SSMParameterPrefix }}/$INSTANCE_ID/nic"
                - |
                  if aws ssm get-parameter --name "$PARAM_NAME" 2>/dev/null; then
                    echo "Parameter already exists"
                    return 0
                  else
                    echo "Parameter does not exist, creating $PARAM_NAME"
                    # Adding to parameter Store in case need to be used in the future
                    aws ssm put-parameter --name "$PARAM_NAME" --type 'String' --value "$NIC"
                    return 0
                  fi

Outputs:
  SupportBucket:
    Description: SupportBucket
    Value: !Ref SupportBucket
    Export:
      Name: !Sub "${ProjectName}-${EnvironmentName}-SupportBucket"

  IAMEC2InstanceProfile:
    Description: IAMEC2InstanceProfile
    Value: !Ref IAMEC2InstanceProfile
    Export:
      Name: !Sub "${ProjectName}-${EnvironmentName}-IAMEC2InstanceProfile"

  IAMEC2InstanceProfileArn:
    Description: IAMEC2InstanceProfileArn
    Value: !GetAtt IAMEC2InstanceProfile.Arn
    Export:
      Name: !Sub "${ProjectName}-${EnvironmentName}-IAMEC2InstanceProfileArn"

  BootstrapSSMDoc:
    Description: Document for SSM
    Value: !Ref BootstrapSSMDoc
    Export:
      Name: !Sub "${ProjectName}-${EnvironmentName}-SSMDoc"
