AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
  EnvironmentName:
    Type: String
  AppValue:
    Type: String
  SupportBucket:
    Type: String
    Description: S3 bucket for support files
  ScriptVersion:
    Type: String
    Default: latest
    Description: Version of bootstrap scripts to use (e.g., v1.0.0 or latest)

Resources:
  # No custom SSM Document - Lambda will use AWS-RunShellScript with inline commands

  NotificationSenderEmailParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /minecraft-dashboard/notification-sender-email
      Type: String
      Value: !Sub "msd@noreply.geckobyte.ca"
      Description: Email address used to send server notifications

Outputs:
  BootstrapDocumentName:
    Description: SSM Document name for bootstrap (managed AWS document)
    Value: AWS-RunShellScript
    Export:
      Name: !Sub "${ProjectName}-${EnvironmentName}-BootstrapDocName"
