name: DeployDev

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    #needs: [deploy-stage]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy
        with:
          config-env: dev
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          pipeline-role: ${{ secrets.PIPELINE_ROLE }}
          deploy-role: ${{ secrets.DEPLOY_ROLE }}